# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='packet.proto',
  package='tutorial',
  syntax='proto3',
  serialized_pb=_b('\n\x0cpacket.proto\x12\x08tutorial\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n\x04Pack\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64istributed\x18\x03 \x01(\t\x12\x30\n\x0clast_updated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\")\n\x07Packets\x12\x1e\n\x06packet\x18\x01 \x03(\x0b\x32\x0e.tutorial.PackBP\n\x14\x63om.example.tutorialB\x11\x41\x64\x64ressBookProtos\xaa\x02$Google.Protobuf.Examples.AddressBookb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_PACK = _descriptor.Descriptor(
  name='Pack',
  full_name='tutorial.Pack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='tutorial.Pack.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='tutorial.Pack.file_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distributed', full_name='tutorial.Pack.distributed', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_updated', full_name='tutorial.Pack.last_updated', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=172,
)


_PACKETS = _descriptor.Descriptor(
  name='Packets',
  full_name='tutorial.Packets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packet', full_name='tutorial.Packets.packet', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=215,
)

_PACK.fields_by_name['last_updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PACKETS.fields_by_name['packet'].message_type = _PACK
DESCRIPTOR.message_types_by_name['Pack'] = _PACK
DESCRIPTOR.message_types_by_name['Packets'] = _PACKETS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pack = _reflection.GeneratedProtocolMessageType('Pack', (_message.Message,), dict(
  DESCRIPTOR = _PACK,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Pack)
  ))
_sym_db.RegisterMessage(Pack)

Packets = _reflection.GeneratedProtocolMessageType('Packets', (_message.Message,), dict(
  DESCRIPTOR = _PACKETS,
  __module__ = 'packet_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Packets)
  ))
_sym_db.RegisterMessage(Packets)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024com.example.tutorialB\021AddressBookProtos\252\002$Google.Protobuf.Examples.AddressBook'))
# @@protoc_insertion_point(module_scope)
